//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int IdProgress { get; set; }
        public int IdPerson { get; set; }
        public int IdDiscipline { get; set; }
        public int Grade { get; set; }
        public System.DateTime DateGrade { get; set; }
        public int Semester { get; set; }

        private DateTime _dateStart;
        public DateTime DateStart
        {
            get
            {
                _dateStart = Convert.ToDateTime("01.01.2022");
                return _dateStart;
            }
            set
            {

            }
        }

        private DateTime _dateEnd;
        public DateTime DateEnd
        {
            get
            {
                _dateEnd = DateTime.Today;
                return _dateEnd;
            }
            set
            {

            }
        }


        public virtual Discipline Discipline { get; set; }
        public virtual Person Person { get; set; }
    }
}
